=== davidgutierrezrubio/jmathanim/src/resources/config/JMathAnimConfig.dtd
<?xml version='1.0' encoding='UTF-8'?>

        <!--
            TODO define vocabulary identification
            PUBLIC ID: -//vendor//vocabulary//EN
            SYSTEM ID: http://server/path/light.dtd

        -->

        <!--
            An example how to use this DTD from your XML document:

            <?xml version="1.0"?>

            <!DOCTYPE JMathAnimConfig SYSTEM "light.dtd">

            <JMathAnimConfig>
            ...
            </JMathAnimConfig>
        -->

        <!--- Entities -->
        <!--- LatexToken types -->

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT JMathAnimConfig (include|video|background|styles|latexStyles|colorMap)*>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT include (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT background (color)*>


        <!ELEMENT video (size|createMovie|showPreviewWindow|limitFPS|printProgressBar)*>


        <!ELEMENT size (color)*>
        <!ATTLIST size width CDATA #REQUIRED>
        <!ATTLIST size height CDATA #REQUIRED>
        <!ATTLIST size fps CDATA #REQUIRED>
        <!ELEMENT createMovie (#PCDATA)>
        <!ELEMENT limitFPS (#PCDATA)>
        <!ELEMENT printProgressBar (#PCDATA)>
        <!ELEMENT showPreviewWindow (#PCDATA)>


        <!--- Put your DTDDoc comment here. -->

        <!ELEMENT color (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT styles (style)*>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT style (color|drawColor|fillColor|thickness|scaleArrowHead1|scaleArrowHead2|dotStyle|dashStyle)*>
        <!ATTLIST style
                name CDATA #IMPLIED
                >

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT drawColor (#PCDATA|linearGradient|radialGradient|getDrawColor|getFillColor)*>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT fillColor (#PCDATA|linearGradient|radialGradient|getDrawColor|getFillColor)*>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT thickness (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT scaleArrowHead1 (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT scaleArrowHead2 (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT dotStyle (#PCDATA)>

        <!--- Put your DTDDoc comment here. -->
        <!ELEMENT dashStyle (#PCDATA)>

        <!ELEMENT getFillColor (#PCDATA)>
        <!ATTLIST getFillColor
                style CDATA #IMPLIED
                >

        <!ELEMENT getDrawColor (#PCDATA)>
        <!ATTLIST getDrawColor
                style CDATA #IMPLIED
                >


        <!ELEMENT linearGradient (start|end|stops)*>
        <!ATTLIST linearGradient
                cycle CDATA #IMPLIED
                relative CDATA #IMPLIED
                >

        <!ELEMENT radialGradient (center|radius|stops)*>
        <!ATTLIST radialGradient
                cycle CDATA #IMPLIED
                relative CDATA #IMPLIED
                >

        <!ELEMENT center (#PCDATA)>
        <!ATTLIST center
                x CDATA #IMPLIED
                y CDATA #IMPLIED
                >
        <!ELEMENT radius (#PCDATA)>


        <!ELEMENT start (#PCDATA)>
        <!ATTLIST start
                x CDATA #IMPLIED
                y CDATA #IMPLIED
                >
        <!ELEMENT end (#PCDATA)>
        <!ATTLIST end
                x CDATA #IMPLIED
                y CDATA #IMPLIED
                >

        <!ELEMENT stops (stop)*>
        <!ELEMENT stop (#PCDATA)>
        <!ATTLIST stop
                t CDATA #IMPLIED
                >


        <!--Colormaps-->
        <!ELEMENT colorMap (colorMapItem)*>
        <!ELEMENT colorMapItem (name|colorDef)*>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT colorDef (#PCDATA)>

        <!--- LatexStyles -->
        <!ELEMENT latexStyles (latexStyle)*>
        <!ELEMENT latexStyle (latexStyleItem)*>
        <!ATTLIST latexStyle
                name CDATA #IMPLIED
                >
        <!ELEMENT latexStyleItem (conditions|style)*>
        <!ELEMENT conditions (equals|equalsPrev|equalsAfter|differs|differsPrev|differsAfter)*>
        <!ELEMENT equals (type|subtype|string)*>
        <!ELEMENT equalsPrev (type|subtype|string)*>
        <!ELEMENT equalsAfter (type|subtype|string)*>
        <!ELEMENT differs (type|subtype|string)*>
        <!ELEMENT differsPrev (type|subtype|string)*>
        <!ELEMENT differsAfter (type|subtype|string)*>

        <!ELEMENT type (#PCDATA)>
        <!ELEMENT subtype (#PCDATA)>
        <!ELEMENT string (#PCDATA)>

=== davidgutierrezrubio/jmathanim/src/resources/config/light.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JMathAnimConfig SYSTEM "JMathAnimConfig.dtd">
<JMathAnimConfig>
    <include>#axes_and_functions_light.xml</include>
    <include>#dots.xml</include>
    <include>#ColorMap_JavaFX.xml</include>
    <background>
        <color>#FDFDFD</color>
    </background>
    <styles>
        <style name="default">
            <drawColor>black</drawColor>
            <fillColor>#00000000</fillColor>
            <thickness>10</thickness>
        </style>
          <style name="dotdefault">
            <drawColor>black</drawColor>
            <fillColor>#00000000</fillColor>
            <thickness>30</thickness>
        </style>  
        <style name="latexdefault">
            <drawColor>black</drawColor>
            <fillColor>black</fillColor>
            <thickness>1</thickness>
        </style>
         <style name="arrowdefault">
            <drawColor>black</drawColor>
            <fillColor>black</fillColor>
            <thickness>4</thickness>
            <scaleArrowHead1>1</scaleArrowHead1>
            <scaleArrowHead2>1</scaleArrowHead2>
        </style>
          <style name="gridPrimaryDefault">
            <drawColor>black</drawColor>
            <fillColor>NONE</fillColor>
            <thickness>2</thickness>
        </style>
        <style name="solidRed">
            <drawColor>black</drawColor>
            <fillColor>#f55652</fillColor>
            <thickness>15</thickness>
        </style>
        <style name="solidBlue">
            <drawColor>black</drawColor>
            <fillColor>#7ca0c0</fillColor>
            <thickness>15</thickness>
        </style>
        <style name="solidGreen">
            <drawColor>black</drawColor>
            <fillColor>#9bc693</fillColor>
            <thickness>15</thickness>
        </style>
        <style name="solidOrange">
            <drawColor>black</drawColor>
            <fillColor>orange</fillColor>
            <thickness>15</thickness>
        </style>
            <style name="1">
            <drawColor>#07004D</drawColor>
            <thickness>30</thickness>
            <dotStyle>circle</dotStyle>
        </style>
        <style name="2">
            <drawColor>#BF2500</drawColor>
            <thickness>30</thickness>
            <dotStyle>cross</dotStyle>
        </style>
        <style name="3">
            <drawColor>#5D2E8C</drawColor>
            <thickness>30</thickness>
            <dotStyle>plus</dotStyle>
        </style>
          <style name="fn1">
            <drawColor>#0F4C5C</drawColor>
            <fillColor>none</fillColor>
            <thickness>8</thickness>
        </style> 
         <style name="fn2">
            <drawColor>#9A031E</drawColor>
            <fillColor>none</fillColor>
            <thickness>8</thickness>
        </style> 
         <style name="fn3">
            <drawColor>#5F0F40</drawColor>
            <fillColor>none</fillColor>
            <dashStyle>DASHED</dashStyle>
            <thickness>4</thickness>
        </style> 
    </styles>
</JMathAnimConfig>

=== davidgutierrezrubio/jmathanim/src/resources/config/dark.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JMathAnimConfig SYSTEM "JMathAnimConfig.dtd">
<JMathAnimConfig>
    <include>#axes_and_functions_dark.xml</include>
    <include>#dots.xml</include>
    <background>
        <color>#000000</color>
    </background>
    <styles>
        <style name="default">
            <drawColor>#FFFFFFFF</drawColor>
            <fillColor>#00000000</fillColor>
            <thickness>10</thickness>
        </style> 
        <style name="dotdefault">
            <drawColor>#FFFFFFFF</drawColor>
            <fillColor>#00000000</fillColor>
            <thickness>30</thickness>
        </style>  
        <style name="latexdefault">
            <drawColor>#FFFFFFFF</drawColor>
            <fillColor>#FFFFFFFF</fillColor>
            <thickness>1</thickness>
        </style>
        <style name="arrowdefault">
            <drawColor>#FFFFFFFF</drawColor>
            <fillColor>#FFFFFFFF</fillColor>
            <thickness>4</thickness>
            <scaleArrowHead1>1</scaleArrowHead1>
            <scaleArrowHead2>1</scaleArrowHead2>
        </style>
    <style name="contourHighlight">
        <drawColor>green</drawColor>
        <fillColor>none</fillColor>
        <thickness>30</thickness>
    </style>
        
        
    <style name="solidRed">
        <drawColor>WHITE</drawColor>
        <fillColor>#f55652</fillColor>
        <thickness>15</thickness>
    </style>
    <style name="solidBlue">
        <drawColor>WHITE</drawColor>
        <fillColor>#7ca0c0</fillColor>
        <thickness>15</thickness>
    </style>
    <style name="solidGreen">
        <drawColor>WHITE</drawColor>
        <fillColor>#9bc693</fillColor>
        <thickness>15</thickness>
    </style>
    <style name="solidOrange">
        <drawColor>WHITE</drawColor>
        <fillColor>orange</fillColor>
        <thickness>15</thickness>
    </style>
    <style name="fn1">
        <drawColor>#277DA1</drawColor>
        <fillColor>none</fillColor>
        <thickness>10</thickness>
    </style> 
    <style name="fn2">
        <drawColor>#F94144</drawColor>
        <fillColor>none</fillColor>
        <thickness>10</thickness>
    </style> 
    <style name="fn3">
        <drawColor>#F9C74F</drawColor>
        <fillColor>none</fillColor>
        <dashStyle>DASHED</dashStyle>
        <thickness>8</thickness>
    </style> 
    </styles>
     <include>#latexStylesDark.xml</include>
</JMathAnimConfig>

=== davidgutierrezrubio/jmathanim/src/resources/config/dots.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JMathAnimConfig SYSTEM "JMathAnimConfig.dtd">
<JMathAnimConfig>  
    <styles>
        <style name="redCircle">
            <drawColor>RED</drawColor>
            <thickness>30</thickness>
            <dotStyle>circle</dotStyle>
        </style>
        <style name="blueCross">
            <drawColor>#6ca2e0</drawColor>
            <thickness>30</thickness>
            <dotStyle>cross</dotStyle>
        </style>
        <style name="yellowPlus">
            <drawColor>#FCE16D</drawColor>
            <thickness>30</thickness>
            <dotStyle>plus</dotStyle>
        </style>
    </styles>
</JMathAnimConfig>
